#
# Copyright 2007 (c) SAEIL Systems Inc. All Rights Reserved.
#
# FILENAME    : iccp.conf
# PRODUCT(S)  : 
# DESCRIPTION : ICCP Configuration
# REVISION HISTORY
#   Date      Who    Rev                       Comments
# ---------- ------  ----  -------------------------------------------
# 2016.04.15 ChoiBC   01   create
#

#
#	ICCP Local Control Center Configuration
#
LocalCC_Name = SDP_TO_FEP
LocalCC_MaxDsTs = 10
LocalCC_MaxDataSets = 10
LocalCC_MaxMmsMsgSize = 32000

#
#	ICCP Remote Control Center Configuration
#
RemoteCC_Name = SDP_TO_FEP
# Version : "1996-08" or "2000-08"
RemoteCC_Version = 2000-08
RemoteCC_BilateralTable_Name = BLT_NAME
RemoteCC_BilateralTable_Id = BLT_ID
RemoteCC_BilateralTable_LocalDomain = DomX
RemoteCC_BilateralTable_RemoteDomain = DomX
RemoteCC_BilateralTable_ShortestInterval = 1
#RemoteCC_Association_Name = Association
RemoteCC_Association_InitiateTimeout = 5
RemoteCC_Association_ConcludeTimeout = 5
RemoteCC_Association_AssocHeartbeatTime = 3
RemoteCC_Association_MaxMmsMsgSize = 32000
RemoteCC_Association_MaxReqPend = 5
RemoteCC_Association_MaxIndPend = 5
RemoteCC_Association_MaxNest = 10
RemoteCC_Association_IdentifyTimeout = 0
RemoteCC_ServerObjects_Scope = VCC			# VCC | ICC
RemoteCC_ServerObjects_Sdi.Name = SDI
RemoteCC_ServerObjects_Sdi.NumberWidth = 3
RemoteCC_ServerObjects_Sdi.Count = 0
RemoteCC_ServerObjects_Sdo.Name = SDO
RemoteCC_ServerObjects_Sdo.NumberWidth = 3
RemoteCC_ServerObjects_Sai.Name = SAI
RemoteCC_ServerObjects_Sai.NumberWidth = 3
RemoteCC_ServerObjects_Ddi.Name = DDI
RemoteCC_ServerObjects_Ddi.NumberWidth = 3
RemoteCC_ServerObjects_Dai.Name = DAI
RemoteCC_ServerObjects_Dai.NumberWidth = 3
RemoteCC_ServerObjects_Qdi.Name = QDI
RemoteCC_ServerObjects_Qdi.NumberWidth = 3
RemoteCC_ServerObjects_Qai.Name = QAI
RemoteCC_ServerObjects_Qai.NumberWidth = 3
RemoteCC_ServerObjects_Tdi.Name = TDI
RemoteCC_ServerObjects_Tdi.NumberWidth = 3
RemoteCC_ServerObjects_Tai.Name = TAI
RemoteCC_ServerObjects_Tai.NumberWidth = 3
RemoteCC_ServerObjects_Dev.Name = DEV
RemoteCC_ServerObjects_Dev.NumberWidth = 3
RemoteCC_ServerObjects_MpuSwitchDevName = SDO0001	# ACE : MPU_SWITCH
RemoteCC_ServerObjects_ChangeOfAnalogPeriod = 5
